<?php

namespace Bramatom\SellingPartnerAmazon;

class AmazonMarketplaceId
{
    const NORTH_AMERICA = 'ATVPDKIKX0DER';
    const EUROPE_UNITED_KINGDOM = 'A1F83G8C2ARO7P';
    const EUROPE_GERMANY = 'A1PA6795UKMFR9';
    const EUROPE_FRANCE = 'A13V1IB3VIYZZH';
    const EUROPE_SPAIN = 'A1RKKUPIHCS9HS';
    const EUROPE_ITALY = 'APJ6JRA9NG5V4';
    const EUROPE_NETHERLANDS = 'A1805IZSGTT6HS';
    const EUROPE_TURKEY = 'A33AVAJ2PDY3EV';
    const EUROPE_POLAND = 'A17BUUBOU051B8';
    const EUROPE_SWEDEN = 'A2L77EE7U53NWQ';
    const EUROPE_IRELAND = 'A1AJWUFUN9MUB2';
    const EUROPE_BELGIUM = 'A2Q3Y263D00KWC';
    const EUROPE_LUXEMBOURG = 'A1AM78C64UM0Y8';
    const EUROPE_PORTUGAL = 'A2EUQ1WTGCTBG2';
    const EUROPE_AUSTRIA = 'A1AT7YVPFBWXBL';
    const EUROPE_FINLAND = 'A1AY7XZ3DQ5V8C';
    const EUROPE_DENMARK = 'A1ARBEBBN255ZZ';
    const EUROPE_SWITZERLAND = 'A1X6FK5RDHNB96';
    const EUROPE_NORWAY = 'A18ENKM3CV7ZOI';
    const EUROPE_CZECH_REPUBLIC = 'A1BKKMFR4GGK3Z';
    const EUROPE_HUNGARY = 'A1N1UUSW8WYK6I';
    const EUROPE_SLOVAKIA = 'A1UQ2QG1KJAMF8';
    const EUROPE_SLOVENIA = 'A1BJZM6MZU6Q1Q';
    const EUROPE_LATVIA = 'A3K9GXZ8XROZRJ';
    const EUROPE_ESTONIA = 'A3RJ1RZXJYGZ9A';
    const EUROPE_LITHUANIA = 'A3K5Y5Y5KB5J5F';
    const EUROPE_BULGARIA = 'A1GGNKT7ZF69JL';
    const EUROPE_ROMANIA = 'A1XJGJ7ZD3P3ZO';
    const EUROPE_GREECE = 'A1FJ1FGZPHK5ZM';
    const EUROPE_ICELAND = 'A1NNEYJ6DYJ6GZ';
    const EUROPE_MALTA = 'A1QQA4HATTTW8M';
}